<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Why KatalonWhy KatalonKatalon is a mode_dda990</name>
   <tag></tag>
   <elementGuidId>0cb7f6b3-3d08-4beb-80bc-d3057c8eb01b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>section.rebrand_header.undefined > div.wrap_container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon_header']/section[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>65f60aed-cc83-4377-90d4-8768e0d53184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wrap_container</value>
      <webElementGuid>5c8e2bf8-17e6-4c24-802f-8da4872662bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Why KatalonWhy KatalonKatalon is a modern, comprehensive quality management platform that helps teams of any size deliver the highest quality digital experiences.Read moreBusiness OutcomesA digital transformation success with software testingSuccess StoriesHow startups to the Fortune 500s launched software fasterEasy, speedFlexibility, ScalabilityVisibilityInnovation &amp; AILow cost, high ROIPlatformPlatformPlatform OverviewModern and comprehensive software quality management platformRead moreTest AuthoringKatalon StudioTest ManagementKatalon TestOpsTest ExecutionKatalon Runtime EngineKatalon TestCloudReporting &amp; AnalyticsKatalon TestOpsApplied Artificial IntelligenceAI Visual TestingSolutionsSolutions OverviewKatalon is a modern, comprehensive quality management platform that helps teams of any size deliver the highest quality digital experiences.Read moreWeb TestingRobust solution for end-to-end web automated testing.API TestingAutomated REST and GraphQL API testing.Mobile TestingClick-and-run cloud environments for native apps and mobile browsers.Desktop TestingTest across desktop, web and mobile in a single project.Visual TestingImproving flaky pixel visual UI comparisons with AI methods.Enterprise App TestingEnsure the quality and reliability of your mission critical Enterprise Applications.IntegrationsPricingResourcesResourcesEventsWebinarsLearningAcademyProduct DocumentationBlogsAPI documentationGet HelpCommunityTechnical SupportGetting StartedView a DemoCompanyAbout UsNewsEventsPartnersCareersLife at KatalonBeing hereAll jobsDownload StudioStart free trial</value>
      <webElementGuid>d1a4326e-9383-497c-9a70-bc19be7caa52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon_header&quot;)/section[@class=&quot;rebrand_header undefined&quot;]/div[@class=&quot;wrap_container&quot;]</value>
      <webElementGuid>61f8062d-ab15-4ba1-ad05-f3e105aa2877</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon_header']/section[2]/div</value>
      <webElementGuid>3e4b1334-984b-4493-b729-7ae34d16de1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::div[1]</value>
      <webElementGuid>93a7db9f-3626-4e0e-b67b-da96c2effe17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact us'])[1]/following::div[1]</value>
      <webElementGuid>6bf7d6af-12a6-42fc-bd37-814b0fb306c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div</value>
      <webElementGuid>5e0b9d31-cf42-4613-ae96-bd313010c0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Why KatalonWhy KatalonKatalon is a modern, comprehensive quality management platform that helps teams of any size deliver the highest quality digital experiences.Read moreBusiness OutcomesA digital transformation success with software testingSuccess StoriesHow startups to the Fortune 500s launched software fasterEasy, speedFlexibility, ScalabilityVisibilityInnovation &amp; AILow cost, high ROIPlatformPlatformPlatform OverviewModern and comprehensive software quality management platformRead moreTest AuthoringKatalon StudioTest ManagementKatalon TestOpsTest ExecutionKatalon Runtime EngineKatalon TestCloudReporting &amp; AnalyticsKatalon TestOpsApplied Artificial IntelligenceAI Visual TestingSolutionsSolutions OverviewKatalon is a modern, comprehensive quality management platform that helps teams of any size deliver the highest quality digital experiences.Read moreWeb TestingRobust solution for end-to-end web automated testing.API TestingAutomated REST and GraphQL API testing.Mobile TestingClick-and-run cloud environments for native apps and mobile browsers.Desktop TestingTest across desktop, web and mobile in a single project.Visual TestingImproving flaky pixel visual UI comparisons with AI methods.Enterprise App TestingEnsure the quality and reliability of your mission critical Enterprise Applications.IntegrationsPricingResourcesResourcesEventsWebinarsLearningAcademyProduct DocumentationBlogsAPI documentationGet HelpCommunityTechnical SupportGetting StartedView a DemoCompanyAbout UsNewsEventsPartnersCareersLife at KatalonBeing hereAll jobsDownload StudioStart free trial' or . = 'Why KatalonWhy KatalonKatalon is a modern, comprehensive quality management platform that helps teams of any size deliver the highest quality digital experiences.Read moreBusiness OutcomesA digital transformation success with software testingSuccess StoriesHow startups to the Fortune 500s launched software fasterEasy, speedFlexibility, ScalabilityVisibilityInnovation &amp; AILow cost, high ROIPlatformPlatformPlatform OverviewModern and comprehensive software quality management platformRead moreTest AuthoringKatalon StudioTest ManagementKatalon TestOpsTest ExecutionKatalon Runtime EngineKatalon TestCloudReporting &amp; AnalyticsKatalon TestOpsApplied Artificial IntelligenceAI Visual TestingSolutionsSolutions OverviewKatalon is a modern, comprehensive quality management platform that helps teams of any size deliver the highest quality digital experiences.Read moreWeb TestingRobust solution for end-to-end web automated testing.API TestingAutomated REST and GraphQL API testing.Mobile TestingClick-and-run cloud environments for native apps and mobile browsers.Desktop TestingTest across desktop, web and mobile in a single project.Visual TestingImproving flaky pixel visual UI comparisons with AI methods.Enterprise App TestingEnsure the quality and reliability of your mission critical Enterprise Applications.IntegrationsPricingResourcesResourcesEventsWebinarsLearningAcademyProduct DocumentationBlogsAPI documentationGet HelpCommunityTechnical SupportGetting StartedView a DemoCompanyAbout UsNewsEventsPartnersCareersLife at KatalonBeing hereAll jobsDownload StudioStart free trial')]</value>
      <webElementGuid>2fa84773-803b-46ab-83ae-e246a9bf4752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
