<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Seamless test automation, superchar_16ba5d</name>
   <tag></tag>
   <elementGuidId>8240684b-904d-47e3-951b-0d691c9ab5fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>section.hero_section</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/section</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>dae80e1f-4094-451c-9312-dc87201c37bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hero_section</value>
      <webElementGuid>c2c38878-ac2c-4b05-b1cf-c23175fe88c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seamless test automation, supercharged by AIWrite tests faster, get clearer insights, and improve coverage with an AI-augmented platform.Start free trialView a demoHelping 30K+ software, DevOps and quality teams test and launch software faster.</value>
      <webElementGuid>c3924288-172c-46a7-be10-b32fda324775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;HomePage_wrapHomePage__zdHwS&quot;]/section[@class=&quot;hero_section&quot;]</value>
      <webElementGuid>cee17b46-b195-4ab7-9e66-2fc29cca4512</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section</value>
      <webElementGuid>b0e544d7-21ad-471e-9c72-51e390d4dfd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All jobs'])[2]/following::section[1]</value>
      <webElementGuid>3a54d825-29a7-4e7c-bd98-c547967c13d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Being here'])[2]/following::section[1]</value>
      <webElementGuid>ce6e49d9-f233-443e-9117-434fc79dc201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/section</value>
      <webElementGuid>a3f0efc7-8f4d-4cc6-afec-9e347b71e70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'Seamless test automation, supercharged by AIWrite tests faster, get clearer insights, and improve coverage with an AI-augmented platform.Start free trialView a demoHelping 30K+ software, DevOps and quality teams test and launch software faster.' or . = 'Seamless test automation, supercharged by AIWrite tests faster, get clearer insights, and improve coverage with an AI-augmented platform.Start free trialView a demoHelping 30K+ software, DevOps and quality teams test and launch software faster.')]</value>
      <webElementGuid>2470750a-68a9-4113-a535-ba610a30343b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
