<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Seamless test automation, supercharged by AI</name>
   <tag></tag>
   <elementGuidId>4bc5eb92-111b-4c7e-9a6e-605f3ecf4886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/section/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.hero_title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>4b962e3f-5756-44a0-8ec5-926da94a6794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hero_title</value>
      <webElementGuid>0d8ef22d-fa65-4a6a-8cc4-1e6d4fe32ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seamless test automation, supercharged by AI</value>
      <webElementGuid>e7216ec0-b85e-41b9-bdd0-bb84b07f3d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;HomePage_wrapHomePage__zdHwS&quot;]/section[@class=&quot;hero_section&quot;]/h1[@class=&quot;hero_title&quot;]</value>
      <webElementGuid>fb95db70-552d-423f-9360-b36731d51134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section/h1</value>
      <webElementGuid>9205975a-0841-46b2-86fa-57d33ff20a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All jobs'])[2]/following::h1[1]</value>
      <webElementGuid>895bfcb8-ca7d-4a44-83e9-06e1fbe80c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Being here'])[2]/following::h1[1]</value>
      <webElementGuid>e4c9dc49-2f41-4a61-a559-f0fdde2a869d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write tests faster, get clearer insights, and improve coverage with an AI-augmented platform.'])[1]/preceding::h1[1]</value>
      <webElementGuid>b637de2e-c2a1-4e4f-a55d-69f2803b33cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seamless test automation,']/parent::*</value>
      <webElementGuid>00b874f8-5d5a-4d04-916b-5d13ec21b371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>2f3eadd3-3b2d-47da-8693-55834a37c3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Seamless test automation, supercharged by AI' or . = 'Seamless test automation, supercharged by AI')]</value>
      <webElementGuid>0ef73498-82f4-4f45-ad80-fb197f1b4e75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
