<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Seamless test automation, supercharged by AI</name>
   <tag></tag>
   <elementGuidId>4bc5eb92-111b-4c7e-9a6e-605f3ecf4886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.hero_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/section/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>9fa03b57-5810-41c9-926a-669f7e032e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hero_title</value>
      <webElementGuid>5d018754-06da-43fa-bc01-a6cb7684fad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seamless test automation, supercharged by AI</value>
      <webElementGuid>50ca2e46-ed53-49fa-afa1-d80b6c6f4c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;HomePage_wrapHomePage__zdHwS&quot;]/section[@class=&quot;hero_section&quot;]/h1[@class=&quot;hero_title&quot;]</value>
      <webElementGuid>27d74e0c-699a-4d5c-8997-fc41428257b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section/h1</value>
      <webElementGuid>673906b5-0aa0-4627-b971-07b3257ff2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All jobs'])[2]/following::h1[1]</value>
      <webElementGuid>5824f9de-5fed-4935-917e-21bbfdcc727e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Being here'])[2]/following::h1[1]</value>
      <webElementGuid>f6f84021-d7a2-49f6-afd4-76d5b3f650b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write tests faster, get clearer insights, and improve coverage with an AI-augmented platform.'])[1]/preceding::h1[1]</value>
      <webElementGuid>e3aec64d-fe87-4b42-9485-6d5eb657c18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seamless test automation,']/parent::*</value>
      <webElementGuid>3b0452bc-6933-4460-bc4f-873a30bd0550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>3db6ae6f-aa6d-4b00-a801-7039d29057d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Seamless test automation, supercharged by AI' or . = 'Seamless test automation, supercharged by AI')]</value>
      <webElementGuid>b741c758-91e2-40b3-bffb-6a2dd62353d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
