<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Try Again</name>
   <tag></tag>
   <elementGuidId>11579186-c87d-40b2-9333-9c0750de1423</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='continue-appSubmitButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;continue-appSubmitButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>524a4a7c-51ec-4500-a58e-db11d775ec9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root pds-button jss6 jss8 submit-btn </value>
      <webElementGuid>867f589d-9544-4183-8411-d64c6a3c8959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3da83c5e-95cd-445f-83cc-410579cb6936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b756bdf5-3df1-4612-8175-7284141d2963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>continue-app-continue-appSubmitButton</value>
      <webElementGuid>07c04952-57fc-4c66-926c-925672c0297a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>continue-app-continue-appSubmitButton</value>
      <webElementGuid>f4285291-1d02-4cde-8cd5-9d5af99c6098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>continue-app-continue-appSubmitButton</value>
      <webElementGuid>9b99403a-b7b5-41ce-8291-99d90ec3a9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continue-appSubmitButton</value>
      <webElementGuid>11ca1854-4dca-4733-883f-d61756ba0bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Try Again</value>
      <webElementGuid>6c556e8c-837a-4ea2-a029-1c803fc17b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pi1-1QAAT&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page page--continue-app&quot;]/div[@class=&quot;page__container&quot;]/div[@class=&quot;page__content&quot;]/form[@class=&quot;page__form&quot;]/div[@class=&quot;page__button-group&quot;]/div[@class=&quot;propulsion-button-group&quot;]/button[@class=&quot;MuiButtonBase-root pds-button jss6 jss8 submit-btn&quot;]</value>
      <webElementGuid>a6ff9d09-9d2b-4d7c-a27a-8b9ba301d63b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='continue-appSubmitButton']</value>
      <webElementGuid>d7cf35e3-89c0-4025-ab6c-8754a80f18f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pi1-1QAAT']/div[2]/div[2]/div/div[3]/form/div[2]/div/button</value>
      <webElementGuid>8074906c-fc80-4b3a-9bbe-16e65e925fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We hit a snag, but your information was saved. Let’s try again'])[1]/following::button[1]</value>
      <webElementGuid>4267b486-c139-482a-9d11-02882d9f9479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loaded. We hit a snag, but your information was saved. Let’s try again'])[1]/following::button[1]</value>
      <webElementGuid>624dc177-e294-4cf2-8af3-d717c7ff807b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='San Francisco, California 94105, USA'])[1]/preceding::button[1]</value>
      <webElementGuid>e9ddf421-11c8-49dd-a01b-ad8fdf745c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>4c056511-e42c-4320-beea-de44cca999d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Try Again']/parent::*</value>
      <webElementGuid>186278bb-4cf5-4a65-a86f-8eead244ebc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>da65e5dc-7124-419d-a8e2-28c51c18c54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'continue-appSubmitButton' and (text() = 'Try Again' or . = 'Try Again')]</value>
      <webElementGuid>42a317ee-40fb-4d6f-a65d-65473ee27b67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
