<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SHOW</name>
   <tag></tag>
   <elementGuidId>ff40a396-2cdd-4777-a43f-5bf0bba96a4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.MuiButtonBase-root.pds-button.jss6.jss10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>127f0b89-976d-46a5-b12e-072a8aade9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root pds-button jss6 jss10</value>
      <webElementGuid>ef32503a-7f4f-42ec-93a5-3d2f9257891d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>54a4ae12-cd08-4500-b6a0-c64c8ec39619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e1292f30-ec96-4d46-a07e-987c041ff884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>position</name>
      <type>Main</type>
      <value>end</value>
      <webElementGuid>d43bb08d-1516-4522-a206-0c62f1befc39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SHOW</value>
      <webElementGuid>402a28d8-875b-4953-9fca-f602bfddd6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pi1-1QAAT&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page page--password&quot;]/div[@class=&quot;page__container&quot;]/div[@class=&quot;page__content&quot;]/form[@class=&quot;page__form&quot;]/div[@class=&quot;page__form-inputs  page__form-inputs--with-btn-subtext&quot;]/div[@class=&quot;form__input password-container&quot;]/div[@class=&quot;MuiFormControl-root pds-text-field MuiFormControl-fullWidth&quot;]/div[@class=&quot;MuiInputBase-root jss23 pds-input Mui-error jss27 MuiInputBase-formControl jss24 MuiInputBase-adornedEnd jss29&quot;]/button[@class=&quot;MuiButtonBase-root pds-button jss6 jss10&quot;]</value>
      <webElementGuid>d69b292c-d503-403a-8743-c8cccdfbc735</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>b0533681-c48e-4d23-9c30-faf651c0158d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pi1-1QAAT']/div[2]/div[2]/div/div[3]/form/div/div[2]/div/div/button</value>
      <webElementGuid>b1dfc81b-6289-4e3d-b098-b0339e0b8643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>0423fe0b-9d63-4ae0-b0ac-c37c53feb291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sreek@lc.com'])[1]/following::button[1]</value>
      <webElementGuid>54bf120b-3519-417b-9c00-2cb895216253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Your Rate'])[1]/preceding::button[2]</value>
      <webElementGuid>287eba4a-ca46-41e1-a44f-cd0348fcdc56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Won’t impact your credit score.*'])[1]/preceding::button[3]</value>
      <webElementGuid>45792313-1b00-4826-a016-77d011f7ab30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SHOW']/parent::*</value>
      <webElementGuid>f66beedd-32d1-4221-a76d-7071058a2456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>fc3af6e8-36c5-4f67-a3bf-d72c9d2abce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'SHOW' or . = 'SHOW')]</value>
      <webElementGuid>f0c4dbab-5ef8-459d-b45f-028b461e5311</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
