<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>940fe09f-f984-466a-bf3e-786cd47967a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='addressSubmitButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;addressSubmitButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64884f5a-7fb6-4184-93c7-ddf23358919e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root pds-button jss6 jss8 submit-btn </value>
      <webElementGuid>919f8783-a982-4613-8516-49fb71ebf455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ee38b30c-3f1b-40a0-b6f0-4cfcfbaf820b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>640c6b0f-e3e9-42a6-b8ac-486657ce1bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>primary-address-addressSubmitButton</value>
      <webElementGuid>573633a0-8ee8-40dc-80da-ac128d31c7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>primary-address-addressSubmitButton</value>
      <webElementGuid>03e87141-cbdd-4aae-8959-85b01937af01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>primary-address-addressSubmitButton</value>
      <webElementGuid>ccca2157-1eab-4cb7-9750-5c49ac44f8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressSubmitButton</value>
      <webElementGuid>5de6f9f5-1f73-42bf-bde9-fbbc5e1d007f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>023a064e-a8f3-4328-9ef8-4dcdf8486785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pi1-1QAAT&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page page--address&quot;]/div[@class=&quot;page__container&quot;]/div[@class=&quot;page__content&quot;]/form[@class=&quot;page__form&quot;]/div[@class=&quot;page__button-group&quot;]/div[@class=&quot;propulsion-button-group&quot;]/button[@class=&quot;MuiButtonBase-root pds-button jss6 jss8 submit-btn&quot;]</value>
      <webElementGuid>ca003f8f-913d-401d-aceb-d01106eeaf5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='addressSubmitButton']</value>
      <webElementGuid>41280335-0ed6-4ab8-be1c-7e4d1749c206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pi1-1QAAT']/div[2]/div[2]/div/div[3]/form/div[2]/div/button[2]</value>
      <webElementGuid>d457874b-ddc7-4925-93e0-c6d0956dbbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip'])[1]/following::button[2]</value>
      <webElementGuid>44f0a3ae-0880-4f3f-a62c-ef21c6e10d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::button[2]</value>
      <webElementGuid>c1e6d84f-f55d-4575-81d5-1164505d696e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='San Francisco, California 94105, USA'])[1]/preceding::button[1]</value>
      <webElementGuid>fb73599a-96be-4a10-a92a-2d4b6075f416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>611ede84-df9d-4770-bb67-448640c46979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>504ff616-ab3b-4036-81b1-4f30fa3c5198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>5007501b-a475-4010-a6b1-1285a2b144d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'addressSubmitButton' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>09ed5a71-7527-4117-97cc-8be97614fab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
