<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>8d32e55c-df28-451a-9c02-28933732c236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='emailPageSubmitButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;emailPageSubmitButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2475833-65b7-4f1b-8c35-42fe12986736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root pds-button jss6 jss8 submit-btn </value>
      <webElementGuid>dfdb3cb3-d82e-4a1e-8bf2-608cd23bd011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>37252291-6561-4266-ad61-a0d73e3f532a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0db573e7-9879-41f9-8b5c-6e460525ef7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>email-emailPageSubmitButton</value>
      <webElementGuid>4522edc8-e415-4d33-9016-dc194cc0fab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>email-emailPageSubmitButton</value>
      <webElementGuid>c0ee93c2-3c26-4359-98bf-8793e5da55e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>email-emailPageSubmitButton</value>
      <webElementGuid>67e04862-8c88-4564-87b7-5d070c089f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailPageSubmitButton</value>
      <webElementGuid>e8279017-d58a-46c3-ba22-b92bb6e51c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>5f187b82-669f-4b0d-b925-b5c8e2ee0af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pi1-1QAAT&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page page--emailPage&quot;]/div[@class=&quot;page__container&quot;]/div[@class=&quot;page__content&quot;]/form[@class=&quot;page__form&quot;]/div[@class=&quot;page__button-group&quot;]/div[@class=&quot;propulsion-button-group&quot;]/button[@class=&quot;MuiButtonBase-root pds-button jss6 jss8 submit-btn&quot;]</value>
      <webElementGuid>0cae49a2-b100-4e12-a87e-6e45bb003d1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='emailPageSubmitButton']</value>
      <webElementGuid>a83ecaa9-20df-492c-90ae-ce71fb2024f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pi1-1QAAT']/div[2]/div[2]/div/div[3]/form/div[2]/div/button[2]</value>
      <webElementGuid>721181f8-3896-4c57-bbfe-15e2488b8379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Profile Authorization'])[1]/following::button[2]</value>
      <webElementGuid>57001cc4-9660-4b77-9c46-91ed43ad8e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::button[2]</value>
      <webElementGuid>a7276b9f-7d00-4ccd-8572-70f60c86daf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='San Francisco, California 94105, USA'])[1]/preceding::button[1]</value>
      <webElementGuid>7997be4a-7fb4-40cc-ab9e-18c516193cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>6a83bfef-58b9-4b54-83bc-4fcc7abd48a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>be1ecf44-ed52-48d4-9280-6da171962061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>4934026e-96ad-4894-80b2-f01caaca366d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'emailPageSubmitButton' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>ad006943-b7cf-4931-ba49-d3ec51beb1c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
