<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next_1_2_3</name>
   <tag></tag>
   <elementGuidId>55d71f87-3d7f-4c2d-a386-cba3b1c75a74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='nameSubmitButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;nameSubmitButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fe22a44e-79e3-4c96-bad1-bbd20cf5ff22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root pds-button jss6 jss8 submit-btn </value>
      <webElementGuid>e6335c78-0aee-402e-8077-ebe4e04d2fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bffd3acd-26e9-45c0-a0b3-74b3da171fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fbdf66b4-92fb-49fe-8a29-fa90f6dee4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>primary-name-nameSubmitButton</value>
      <webElementGuid>841060c1-4e86-4e50-ad5b-005387ac0153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>primary-name-nameSubmitButton</value>
      <webElementGuid>b324babc-b589-447c-a1c6-5b3c6b9f0dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>primary-name-nameSubmitButton</value>
      <webElementGuid>9d8d1782-8a34-4f9a-839c-238eae9941ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nameSubmitButton</value>
      <webElementGuid>45668c12-e80d-4fb0-8039-554ca6de2dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>bff4c2bd-13c3-4ed7-891c-7900fd0dff29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pi1-1QAAT&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page page--name&quot;]/div[@class=&quot;page__container&quot;]/div[@class=&quot;page__content&quot;]/form[@class=&quot;page__form&quot;]/div[@class=&quot;page__button-group&quot;]/div[@class=&quot;propulsion-button-group&quot;]/button[@class=&quot;MuiButtonBase-root pds-button jss6 jss8 submit-btn&quot;]</value>
      <webElementGuid>70e28162-8330-4a59-a6ee-e078a3bba9ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='nameSubmitButton']</value>
      <webElementGuid>82af64a0-ab77-476e-8538-dc983b708b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pi1-1QAAT']/div[2]/div[2]/div/div[3]/form/div[2]/div/button[2]</value>
      <webElementGuid>4fbacad2-b018-4778-b83f-e805cc68ffce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We know that your information is personal, so we use bank-level encryption at all times.'])[1]/following::button[2]</value>
      <webElementGuid>d71e9b38-9530-4e9e-86c8-2166c42a5c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::button[2]</value>
      <webElementGuid>136196d3-59b7-4164-b5d7-2d90e952470c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='San Francisco, California 94105, USA'])[1]/preceding::button[1]</value>
      <webElementGuid>a4015a85-eab4-4d6c-b2c2-d26c77a339e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>90526005-8ce6-4adf-af53-90d9b30966aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>ea963bd5-ca9e-4088-8d10-ae90c10e085b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>9fe6ef75-c778-464b-b0a1-d925208842b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'nameSubmitButton' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>1d7c5d6f-096b-4d19-9b40-35980557c2b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
