<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Whats your total annual income, before _95614d</name>
   <tag></tag>
   <elementGuidId>d211994b-80f9-4920-8c3b-5626b1bb8b64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pi1-1QAAT']/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8118dddb-5d5e-400c-82b3-7d39d3c2b29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page page--income </value>
      <webElementGuid>0fe852e3-b4f3-407a-9c9d-8ed31a3c5a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What’s your total annual income, before taxes?Understanding your total income from all sources helps us personalize the best loan offer for you.Total Annual Income$What can I include as total annual income?Some examples of income include the following:Income from employment, including full-time, part-time, freelance, or seasonal jobsSelf-employment, including any business dividends or rental incomeNon-taxable income, if included, should be increased by 25%Any other income such as retirement, social security, public assistance, or any non-taxable incomeOnly include alimony, child support, or separate maintenance if you wish for us to consider it as a source of repaymentNext</value>
      <webElementGuid>c32a9920-ec66-43e2-b2ca-f907830bdcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pi1-1QAAT&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page page--income&quot;]</value>
      <webElementGuid>a4348a25-b76d-4251-8c3e-217fadd021de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pi1-1QAAT']/div[2]/div[2]</value>
      <webElementGuid>33b5ba56-434d-4433-8f57-60afe197384c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What’s your total annual income, before taxes?'])[1]/following::div[8]</value>
      <webElementGuid>98c2ddac-9849-4114-8fd8-4f9ee1efcf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[2]/following::div[12]</value>
      <webElementGuid>7e636448-eb45-46dc-8795-8aedb96ade14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]</value>
      <webElementGuid>b607e311-f646-4c78-97fe-547bec67b0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'What’s your total annual income, before taxes?Understanding your total income from all sources helps us personalize the best loan offer for you.Total Annual Income$What can I include as total annual income?Some examples of income include the following:Income from employment, including full-time, part-time, freelance, or seasonal jobsSelf-employment, including any business dividends or rental incomeNon-taxable income, if included, should be increased by 25%Any other income such as retirement, social security, public assistance, or any non-taxable incomeOnly include alimony, child support, or separate maintenance if you wish for us to consider it as a source of repaymentNext' or . = 'What’s your total annual income, before taxes?Understanding your total income from all sources helps us personalize the best loan offer for you.Total Annual Income$What can I include as total annual income?Some examples of income include the following:Income from employment, including full-time, part-time, freelance, or seasonal jobsSelf-employment, including any business dividends or rental incomeNon-taxable income, if included, should be increased by 25%Any other income such as retirement, social security, public assistance, or any non-taxable incomeOnly include alimony, child support, or separate maintenance if you wish for us to consider it as a source of repaymentNext')]</value>
      <webElementGuid>41c9336a-1be4-46e0-93c8-af59ae44e264</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
