<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password_1</name>
   <tag></tag>
   <elementGuidId>06e8dfa0-f0ea-4a03-a23c-a778d4495e2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#password-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>914a75ed-f875-4167-9c6a-4d40cfe69bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>63730aa4-d2d4-4818-a2a7-6deface67bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>password-password-helper-text</value>
      <webElementGuid>b5abdec0-d8b9-4340-87dd-6e9647313f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f46dce21-1009-44ce-a95e-b0593667a403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-password</value>
      <webElementGuid>d3e08fe8-9bbe-45ac-827f-2af443fd1375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ca431e2d-07f6-4cb7-b330-3bfa53495df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Create password</value>
      <webElementGuid>46c95cc6-2583-4ddd-91e1-868e685d6f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebf235d1-fcf7-4648-9c96-9d97711be5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>password-password</value>
      <webElementGuid>7e6d268c-7899-4f08-85f5-2421d9d2561f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>password-password</value>
      <webElementGuid>534dab88-944d-41e8-9ac6-994dd142b3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>password-password</value>
      <webElementGuid>d0f72fe4-0a96-40e7-a256-ff46ebae68fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nid-target</name>
      <type>Main</type>
      <value>password-password</value>
      <webElementGuid>a5d9aa84-3c16-40b7-a38e-9638221d7f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>3c7e57d6-1084-4463-b8aa-492ce0797144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input jss31 MuiInputBase-inputAdornedEnd jss34</value>
      <webElementGuid>d7b5a4e1-68c7-46c1-878e-58b7cf3a984d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>97552db0-c223-45e6-bc87-ddd6d8449374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-password&quot;)</value>
      <webElementGuid>ba352e33-3379-499e-ad94-7021979ef18e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password-password']</value>
      <webElementGuid>572f2b9b-488b-4721-9e43-5b9cf0d052e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pi1-1QAAT']/div[2]/div[2]/div/div[3]/form/div/div[2]/div/div/input</value>
      <webElementGuid>af6ecc57-fabf-43c0-a7c5-14aadbbda692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>92628d25-dbc9-4cd8-acc1-d7f0c1f751ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'password-password' and @name = 'password' and @placeholder = 'Create password' and @type = 'text']</value>
      <webElementGuid>47332af1-34ad-4be8-8386-cadc15ec83ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
