<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Address_streetAddress</name>
   <tag></tag>
   <elementGuidId>ef106ca3-b6df-4bce-8834-b73b2d1fce2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='primary-address-streetAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#primary-address-streetAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7bf42f5-de0a-47fa-8c71-9c971f5eba2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a46eb57a-fd42-4136-847d-1111df6159ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2aee5efa-3626-417d-810a-ca98784b17f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primary-address-streetAddress</value>
      <webElementGuid>013d4ce1-aed6-4615-b908-98939e6440e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>streetAddress</value>
      <webElementGuid>fc9e527c-c036-4678-b7e7-f89feecbc99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a0979c2-43b0-4dcb-b58e-4df08f89085e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>primary-address-streetAddress</value>
      <webElementGuid>95a1ad60-f19f-486f-b27c-0eb95edafa06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>primary-address-streetAddress</value>
      <webElementGuid>e1fa4874-5ed1-4795-ab90-edba95c08d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>streetAddress</value>
      <webElementGuid>e2763d62-9e2a-4afd-90f2-355939eccaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nid-target</name>
      <type>Main</type>
      <value>streetAddress</value>
      <webElementGuid>59eafcaa-afb6-41f1-8043-543dad641779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>66d88c35-06a7-453e-a969-5b96d62faa3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input jss31</value>
      <webElementGuid>4344c2e2-3643-408c-8266-d5e5aea775f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-address-streetAddress&quot;)</value>
      <webElementGuid>98d47b13-22e7-43b3-8680-951b48f6314e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='primary-address-streetAddress']</value>
      <webElementGuid>187880b7-987b-49bf-b79f-59977b3cfb25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pi1-1QAAT']/div[2]/div[2]/div/div[3]/form/div/div/div/div/div/div/div/input</value>
      <webElementGuid>0796ab42-e554-4624-9126-585cf753dc00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a3f8b334-a261-4d24-859d-406bc86e8bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'primary-address-streetAddress' and @name = 'streetAddress' and @type = 'text']</value>
      <webElementGuid>db42853c-0007-4237-a5b7-0f15de80e682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
