<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__income</name>
   <tag></tag>
   <elementGuidId>4d69dc9a-3be0-4cf4-9c7d-06d10224a800</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='primary-income-income']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#primary-income-income</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2867f145-7ef2-45db-9afd-5d2f1389c2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>101ef827-c983-41df-8ecd-c00eea87056f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f9ebf93c-aef0-4107-b9d0-d9c54f4e7a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primary-income-income</value>
      <webElementGuid>5f7ff4a4-d952-48a7-aee3-1c4d0a308514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>income</value>
      <webElementGuid>d9815a9a-98ce-4cb2-b01d-83487e1ef71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>64e5ab1e-d949-4d5f-b4e2-b6bc18b55831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>46916a3d-dd39-48ae-a2bc-1c690238ec2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>primary-income-income</value>
      <webElementGuid>0ca6c242-256f-4c88-b176-357d22af6d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>primary-income-income</value>
      <webElementGuid>099430ee-bb1e-4c92-acd5-7353844f181c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>primary-income-income</value>
      <webElementGuid>8e013d2e-e2fe-488b-8749-3d78ab955751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nid-target</name>
      <type>Main</type>
      <value>primary-income-income</value>
      <webElementGuid>a01ff2e3-ec7e-43c1-b63c-b6f5a610aa5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input jss31 MuiInputBase-inputAdornedStart jss33</value>
      <webElementGuid>643c1a64-42fb-491d-bb64-0e80d3a97472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-income-income&quot;)</value>
      <webElementGuid>b4b3ddad-a248-4d76-a273-f4e50adce646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='primary-income-income']</value>
      <webElementGuid>a84bc9ec-9eb9-4674-8a93-443a8dae4e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pi1-1QAAT']/div[2]/div[2]/div/div[3]/form/div/div/div/div/div/input</value>
      <webElementGuid>c807a21b-01d9-4553-b31c-767fd6a9b145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f9c7d3c3-5b36-413d-8854-d295e615ae6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'primary-income-income' and @name = 'income' and @type = 'tel']</value>
      <webElementGuid>0ccdb319-ffa1-4d2d-b37d-056e226a7a31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
