<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Home</name>
   <tag></tag>
   <elementGuidId>99e33039-74cc-4a38-bf08-95281e878a2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='pl-footer']/div/div/div[2]/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.pl-footer-nav-li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a38c73e7-ccf7-41b2-9d32-ed34a6a109c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pl-footer-nav-li</value>
      <webElementGuid>c36c0dbe-fd75-4fcb-9829-1351b341611d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>1aa6018c-9a31-4c91-8ddc-ea9509d414cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pl-footer&quot;)/div[@class=&quot;pl-footer-outer pl-footer-outer--sky&quot;]/div[@class=&quot;pl-footer pl-footer--sky&quot;]/div[@class=&quot;pl-footer-right pl-footer-right--sky&quot;]/ul[@class=&quot;pl-footer-nav pl-footer-nav--sky&quot;]/li[@class=&quot;pl-footer-nav-li&quot;]</value>
      <webElementGuid>f1eaaec2-3e59-49ae-a58a-11b94199b5b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='pl-footer']/div/div/div[2]/ul/li</value>
      <webElementGuid>d3155322-3e93-449f-b04a-eacbbb619ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='San Francisco, California 94105, USA'])[1]/following::li[1]</value>
      <webElementGuid>ddecd962-a997-42fb-99d6-71a45f8e16f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Again'])[1]/following::li[1]</value>
      <webElementGuid>896e74c0-90a7-4fc9-8242-1e7948556eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::li[1]</value>
      <webElementGuid>592984c5-5d84-4c92-8d0f-1caa5225b80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div[2]/ul/li</value>
      <webElementGuid>900ac338-86eb-4698-98f8-cb867d31b3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>7d4e6a24-d43e-4183-87e1-9ad909a7f00d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
