<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Agnes Ln, Albany, NY</name>
   <tag></tag>
   <elementGuidId>68f81dee-348b-4a09-9660-db2deb92a412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='react-autowhatever-1--item-0']/span/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ad47ca56-471d-4dc7-8792-83673cde751a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Agnes Ln, Albany, NY</value>
      <webElementGuid>378a366f-ec6e-4d3f-944f-aa37d91d7b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-autowhatever-1--item-0&quot;)/span[1]/span[2]</value>
      <webElementGuid>08cb86da-c8bf-4d51-b3b4-6c04b297be7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='react-autowhatever-1--item-0']/span/span[2]</value>
      <webElementGuid>df7830c6-e5f2-495d-ba18-0d00a7dbe74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='St'])[1]/following::span[1]</value>
      <webElementGuid>e32c9a88-f600-4459-a240-6b59e634f8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Street Address'])[1]/following::span[3]</value>
      <webElementGuid>bf49f35d-1a72-4535-ab2f-035b9a20bade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='St'])[2]/preceding::span[2]</value>
      <webElementGuid>e78b9b5c-a8e7-4569-a9f8-4db6c3a705c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Albans Rd, Corinna, ME'])[1]/preceding::span[2]</value>
      <webElementGuid>a4bac3f7-5799-4462-8ff0-cbe8668c19ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agnes Ln, Albany, NY']/parent::*</value>
      <webElementGuid>2f962399-b8ab-4ad1-8a8b-fff1dfe912da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>73286df2-8388-4dbe-affa-c3133252c71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Agnes Ln, Albany, NY' or . = ' Agnes Ln, Albany, NY')]</value>
      <webElementGuid>53fa9109-a7f3-4f65-9b54-0f8cd7ffbee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
