<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>335806b0-55ad-42e7-8e19-a3176aed4513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Katalon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aaf921fb-8c0b-4ed7-b183-e9ad959cf199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/logo_kat/katalon-logo-newbrand2022-top-nav.png</value>
      <webElementGuid>e9488496-e132-45cc-849c-31c84db1f22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Katalon</value>
      <webElementGuid>6d056cd3-7654-4e05-96f8-df16cb6a47b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;SignUp_wrapSignup__nLnnj&quot;]/div[@class=&quot;logo_production_katalon&quot;]/a[1]/img[1]</value>
      <webElementGuid>07658f60-0562-49e6-b492-82b2ec61d9ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/a/img</value>
      <webElementGuid>e7121144-ae05-46a1-a42c-a5ae12c2bd2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Katalon']</value>
      <webElementGuid>2370b209-5f99-48ad-98f0-c3f3a198197d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>4a74b891-f0c7-4358-8fa8-db1ffd96376c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/logo_kat/katalon-logo-newbrand2022-top-nav.png' and @alt = 'Katalon']</value>
      <webElementGuid>243802d4-e4ec-4f0e-9bdd-5fef369c8117</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
