<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Check Your Rate</name>
   <tag></tag>
   <elementGuidId>3040d413-c388-4db5-a254-3ecf8c33909e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.heroHomePrequal_submitBtn__nf_Pm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>daf0a150-ff43-40d6-8ec1-0d297b182fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>05f604d2-3d48-4ab7-ab96-ad68c53ce421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>check-rate</value>
      <webElementGuid>0c255f07-59e0-4197-b57f-30f869bcec87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heroHomePrequal_submitBtn__nf_Pm</value>
      <webElementGuid>acf9c064-0041-41b9-bc5d-d37059a88260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>submit-rate</value>
      <webElementGuid>d4262559-8592-4e02-83ac-74493bfa39fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check Your Rate</value>
      <webElementGuid>141acf0e-7e51-4cb9-9290-9337390ea4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;main_main__ySTOf&quot;]/div[1]/div[@class=&quot;main_landingPage__FzqUD&quot;]/div[@class=&quot;main_components__uw_Rm&quot;]/div[2]/div[@class=&quot;websiteComponent_transparent__F4rbk websiteComponent_heroHome__xU4FF&quot;]/div[@class=&quot;websiteComponent_container__86vk_&quot;]/div[@class=&quot;websiteComponent_section__ZfqD8&quot;]/section[@class=&quot;heroHomeTemplate_heroPrequalWithMultipleImages___8P3T&quot;]/div[@class=&quot;heroHomeTemplate_sectionContainer__eo_3_&quot;]/div[@class=&quot;heroHomeTemplate_heroPrequalWithMultipleImagesLeft__F_Jly&quot;]/div[@class=&quot;heroHomePrequal_heroPrequal__POmpI heroHomePrequal_heroPrequalDocked__JEFwC&quot;]/div[@class=&quot;heroHomePrequal_heroPrequalForm__AFLkP&quot;]/div[@class=&quot;heroHomePrequal_prequalHorizontalForm__C30C3&quot;]/div[@class=&quot;MuiGrid-root-11 MuiGrid-container-12 MuiGrid-spacing-xs-2-35&quot;]/div[@class=&quot;MuiGrid-root-11 MuiGrid-item-13 MuiGrid-grid-xs-12-57 MuiGrid-grid-sm-4-63&quot;]/button[@class=&quot;heroHomePrequal_submitBtn__nf_Pm&quot;]</value>
      <webElementGuid>cc7c69ee-8335-4889-b0fe-3d73408983ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>3b246999-4913-478e-b515-274b66660dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div/div[2]/div/div/div/section/div/div/div[2]/div[2]/div/div/div[3]/button</value>
      <webElementGuid>e8396a52-33db-4811-88c8-16596f867b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal loans up to $40,000'])[1]/following::button[1]</value>
      <webElementGuid>1fc03adf-c1b9-49eb-ab3f-71b1388eef6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check your rate. It won’t impact your credit score.'])[1]/following::button[1]</value>
      <webElementGuid>321bfe56-1e49-4268-b49f-daf3d89f97de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Respond to Mail Offer'])[1]/preceding::button[1]</value>
      <webElementGuid>c9b411ea-a29c-4abc-8ec2-8ccf18ddfc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$40,000'])[1]/preceding::button[1]</value>
      <webElementGuid>88915380-8ea7-42c3-a8da-1e2d6d8b5980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check Your Rate']/parent::*</value>
      <webElementGuid>bce7e722-5eaf-4584-8294-15cc69abd787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>95cc1ee4-775e-4278-bc51-c4ebc7fcc53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Check Your Rate' or . = 'Check Your Rate')]</value>
      <webElementGuid>034336e1-b805-4479-8331-7d00c0c46b7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
