<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Personal loans up to 40,000_currencyi_a299bf</name>
   <tag></tag>
   <elementGuidId>22b0000e-6de0-4029-96a3-37d03001063b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.currencyinput_input__oakAL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ddba4a9-05df-43b6-a2d2-b8041220cd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>loan-amount</value>
      <webElementGuid>6b70cb3c-d897-4b87-a9fd-fc9f4a61eceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Loan Amount</value>
      <webElementGuid>6ba26d7a-34d2-45de-8f19-b8ca2b2c1db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Up to $40,000</value>
      <webElementGuid>6c16b1ef-823a-423e-82de-e84f8972b22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>currencyinput_input__oakAL</value>
      <webElementGuid>07e815b0-feb5-41c5-a1a5-ed3219eda2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;main_main__ySTOf&quot;]/div[1]/div[@class=&quot;main_landingPage__FzqUD&quot;]/div[@class=&quot;main_components__uw_Rm&quot;]/div[2]/div[@class=&quot;websiteComponent_transparent__F4rbk websiteComponent_heroHome__xU4FF&quot;]/div[@class=&quot;websiteComponent_container__86vk_&quot;]/div[@class=&quot;websiteComponent_section__ZfqD8&quot;]/section[@class=&quot;heroHomeTemplate_heroPrequalWithMultipleImages___8P3T&quot;]/div[@class=&quot;heroHomeTemplate_sectionContainer__eo_3_&quot;]/div[@class=&quot;heroHomeTemplate_heroPrequalWithMultipleImagesLeft__F_Jly&quot;]/div[@class=&quot;heroHomePrequal_heroPrequal__POmpI heroHomePrequal_heroPrequalDocked__JEFwC&quot;]/div[@class=&quot;heroHomePrequal_heroPrequalForm__AFLkP&quot;]/div[@class=&quot;heroHomePrequal_prequalHorizontalForm__C30C3&quot;]/div[@class=&quot;MuiGrid-root-11 MuiGrid-container-12 MuiGrid-spacing-xs-2-35&quot;]/div[@class=&quot;MuiGrid-root-11 heroHomePrequal_inputAmountGrid__7Xk__ MuiGrid-item-13 MuiGrid-grid-xs-12-57 MuiGrid-grid-sm-3-62&quot;]/div[@class=&quot;currencyinput_wrapper__wuZCD  currencyinput_focusWrapper__YMl11 currencyinput_homePrequalCurrency__UCebE&quot;]/input[@class=&quot;currencyinput_input__oakAL&quot;]</value>
      <webElementGuid>8cbd1c49-b229-4f46-a23d-bbb0ff32cacc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>406d7a6f-34ea-4e09-9685-14d0e80d689d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div/div[2]/div/div/div/section/div/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>a9d46652-ed60-425b-818b-fa0c52ff0afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>78094659-3b57-4af7-be35-e4395790f753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Up to $40,000']</value>
      <webElementGuid>c7613a4c-7f14-4d57-a4ea-1831d4f04d4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
