<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Whats the money forCredit card refin_9ce23e</name>
   <tag></tag>
   <elementGuidId>27c8a549-059a-49f0-8a8a-02a78e18d243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div/div[2]/div/div/div/section/div/div/div[2]/div[2]/div/div/div[2]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.dropdown_select__MIimF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4249ad70-cbcf-4d94-9bdb-3d2bf186e02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>loan-purpose</value>
      <webElementGuid>577314dc-9ea6-4d52-8e38-d26818fd66c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>loan purpose</value>
      <webElementGuid>b539fbcd-f501-4bae-86eb-0e7b26328aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_select__MIimF</value>
      <webElementGuid>df3a6198-a739-490c-ae74-35fa6331eb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What's the money for?Credit card refinancingDebt consolidationHome improvementMajor purchaseHome buyingCar financingGreen loanBusinessVacationMoving and relocationMedical expensesOther</value>
      <webElementGuid>d1f4eb08-dcc7-4107-8f08-6b5069d984d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;main_main__ySTOf&quot;]/div[1]/div[@class=&quot;main_landingPage__FzqUD&quot;]/div[@class=&quot;main_components__uw_Rm&quot;]/div[2]/div[@class=&quot;websiteComponent_transparent__F4rbk websiteComponent_heroHome__xU4FF&quot;]/div[@class=&quot;websiteComponent_container__86vk_&quot;]/div[@class=&quot;websiteComponent_section__ZfqD8&quot;]/section[@class=&quot;heroHomeTemplate_heroPrequalWithMultipleImages___8P3T&quot;]/div[@class=&quot;heroHomeTemplate_sectionContainer__eo_3_&quot;]/div[@class=&quot;heroHomeTemplate_heroPrequalWithMultipleImagesLeft__F_Jly&quot;]/div[@class=&quot;heroHomePrequal_heroPrequal__POmpI heroHomePrequal_heroPrequalDocked__JEFwC&quot;]/div[@class=&quot;heroHomePrequal_heroPrequalForm__AFLkP&quot;]/div[@class=&quot;heroHomePrequal_prequalHorizontalForm__C30C3&quot;]/div[@class=&quot;MuiGrid-root-11 MuiGrid-container-12 MuiGrid-spacing-xs-2-35&quot;]/div[@class=&quot;MuiGrid-root-11 heroHomePrequal_dowpdownGrid__Bf2mG MuiGrid-item-13 MuiGrid-grid-xs-12-57 MuiGrid-grid-sm-5-64&quot;]/div[@class=&quot;dropdown_wrapper__g4QjT heroHomeDropdown   dropdown_shadow__S3qyq dropdown_homePrequalDropdown__YFplT&quot;]/select[@class=&quot;dropdown_select__MIimF&quot;]</value>
      <webElementGuid>1bd42024-db36-4a01-82b0-fd254a8c45fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div/div[2]/div/div/div/section/div/div/div[2]/div[2]/div/div/div[2]/div/select</value>
      <webElementGuid>8aabcf70-34f5-47ae-bd62-4191fc1e4742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal loans up to $40,000'])[1]/following::select[1]</value>
      <webElementGuid>be878f8f-163f-4353-88a5-5b2763925a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check your rate. It won’t impact your credit score.'])[1]/following::select[1]</value>
      <webElementGuid>736640e8-8211-44a3-981d-7fb09a6c3e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Your Rate'])[1]/preceding::select[1]</value>
      <webElementGuid>df1bfe84-e928-4a2a-b6af-4b3f7f96ba9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Respond to Mail Offer'])[1]/preceding::select[1]</value>
      <webElementGuid>2f2d12c1-b29b-4ca4-a186-cbe811195cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7f644458-8dc9-40ad-b709-d8dd18feef27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = concat(&quot;What&quot; , &quot;'&quot; , &quot;s the money for?Credit card refinancingDebt consolidationHome improvementMajor purchaseHome buyingCar financingGreen loanBusinessVacationMoving and relocationMedical expensesOther&quot;) or . = concat(&quot;What&quot; , &quot;'&quot; , &quot;s the money for?Credit card refinancingDebt consolidationHome improvementMajor purchaseHome buyingCar financingGreen loanBusinessVacationMoving and relocationMedical expensesOther&quot;))]</value>
      <webElementGuid>2c88f302-afe1-4111-9da1-c074b1f2c4cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
